before:
  hooks:
    - go mod tidy
builds:
  - binary: bin/backlink
    main: ./backlink.go
    id: macos
    goos:
      - darwin
    goarch:
      - amd64
  - binary: bin/backlink
    main: ./backlink.go
    id: linux
    goos:
      - linux
    goarch:
      - 386
      - arm
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
  - binary: bin/backlink
    main: ./backlink.go
    id: windows
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm64
archives:
  - id: nix
    builds:
      - macos
      - linux
    name_template: backlink_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
  - id: windows
    builds:
      - windows
    name_template: backlink_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE
release:
  prerelease: auto
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
